Repository apple/swift-nio-ssl, pull requests merged in 2019-04, with the labels that each got.

#97 Update BoringSSL to ad9eee1628aa4dac2ac3528cb6bb5ddf27e73560.
  Package.swift
  Sources/CNIOBoringSSL/crypto/asn1/a_int.c
  Sources/CNIOBoringSSL/crypto/asn1/asn1_lib.c
  Sources/CNIOBoringSSL/crypto/bytestring/cbb.c
  Sources/CNIOBoringSSL/crypto/cipher_extra/e_aesccm.c
  Sources/CNIOBoringSSL/crypto/cipher_extra/e_aesctrhmac.c
  Sources/CNIOBoringSSL/crypto/cipher_extra/e_aesgcmsiv.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/aes/internal.h
  Sources/CNIOBoringSSL/crypto/fipsmodule/bn/ctx.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/bn/exponentiation.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/bsaes-armv7.ios.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/bsaes-armv7.linux.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/bsaes-x86_64.linux.x86_64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/bsaes-x86_64.mac.x86_64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/cipher/e_aes.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/cipher/internal.h
  Sources/CNIOBoringSSL/crypto/fipsmodule/digest/md32_common.h
  Sources/CNIOBoringSSL/crypto/fipsmodule/ghash-neon-armv8.ios.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/ghash-neon-armv8.linux.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/md4/md4.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/md5/md5.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/modes/internal.h
  Sources/CNIOBoringSSL/crypto/fipsmodule/rand/ctrdrbg.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha/sha1.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha/sha256.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha/sha512.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/vpaes-x86_64.linux.x86_64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/vpaes-x86_64.mac.x86_64.S
  Sources/CNIOBoringSSL/crypto/stack/stack.c
  Sources/CNIOBoringSSL/hash.txt
  Sources/CNIOBoringSSL/include/CNIOBoringSSL/asn1.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL/bytestring.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL/md4.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL/md5.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL/ripemd.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL/sha.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL/ssl.h
  Sources/CNIOBoringSSL/include/boringssl_prefix_symbols.h
  Sources/CNIOBoringSSL/include/boringssl_prefix_symbols_asm.h
  Sources/CNIOBoringSSL/include/boringssl_prefix_symbols_nasm.inc
  Sources/CNIOBoringSSL/ssl/internal.h
  Sources/CNIOBoringSSL/ssl/ssl_versions.cc
  Sources/CNIOBoringSSL/ssl/t1_lib.cc
Labels: patch-version-bump-only

#99 prevent duplicate targets: rename NIOHTTP1Client to NIOSSLHTTP1Client
  Package.swift
  Sources/NIOSSLHTTP1Client/README.md
  Sources/NIOSSLHTTP1Client/main.swift
Labels: patch-version-bump-only

#98 Expose callback for SSLKEYLOGFILE.
  Sources/NIOSSL/SSLCallbacks.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest+XCTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
Labels: needs-minor-version-bump

#100 Add a timeout for TLS shutdown.
  Sources/NIOSSL/NIOSSLClientHandler.swift
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/NIOSSLServerHandler.swift
  Sources/NIOSSL/SSLErrors.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest+XCTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
Labels: 🔼 needs-minor-version-bump

#102 Avoid using un-thread-safe static buffers when printing errors.
  Sources/NIOSSL/SSLErrors.swift
Labels: patch-version-bump-only

#103 Add 'Show on GitHub' link to API docs
  scripts/generate_docs.sh
Labels: patch-version-bump-only
