Repository apple/swift-nio-ssl, pull requests merged in 2019-03, with the labels that each got.

#73 Rename SSLContext to NIOSSLContext
  Sources/NIOOpenSSL/OpenSSLClientHandler.swift
  Sources/NIOOpenSSL/OpenSSLServerHandler.swift
  Sources/NIOOpenSSL/SSLConnection.swift
  Sources/NIOOpenSSL/SSLContext.swift
  Sources/NIOTLSServer/main.swift
  Tests/NIOOpenSSLTests/ClientSNITests.swift
  Tests/NIOOpenSSLTests/OpenSSLALPNTest.swift
  Tests/NIOOpenSSLTests/OpenSSLIntegrationTest.swift
  Tests/NIOOpenSSLTests/TLSConfigurationTest.swift
  Tests/NIOOpenSSLTests/UnwrappingTests.swift
Labels: needs-major-version-bump

#74 Removed vestigial CNIOOpenSSL module.
  Sources/CNIOOpenSSL/helpers.c
  Sources/CNIOOpenSSL/include/c_nio_openssl.h
  Sources/CNIOOpenSSL/shims.c
Labels: patch-version-bump-only

#75 Rename everything.
  Package.swift
  README.md
  Sources/NIOSSL/ByteBufferBIO.swift
  Sources/NIOSSL/IdentityVerification.swift
  Sources/NIOSSL/LinuxCABundle.swift
  Sources/NIOSSL/NIOSSLClientHandler.swift
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/NIOSSLServerHandler.swift
  Sources/NIOSSL/PosixPort.swift
  Sources/NIOSSL/SSLCertificate.swift
  Sources/NIOSSL/SSLConnection.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/SSLErrors.swift
  Sources/NIOSSL/SSLInit.swift
  Sources/NIOSSL/SSLPKCS12Bundle.swift
  Sources/NIOSSL/SSLPrivateKey.swift
  Sources/NIOSSL/SSLPublicKey.swift
  Sources/NIOSSL/SSLVerificationCallbacks.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Sources/NIOTLSServer/main.swift
  Tests/LinuxMain.swift
  Tests/NIOSSLTests/ByteBufferBIOTest+XCTest.swift
  Tests/NIOSSLTests/ByteBufferBIOTest.swift
  Tests/NIOSSLTests/CertificateVerificationTests+XCTest.swift
  Tests/NIOSSLTests/CertificateVerificationTests.swift
  Tests/NIOSSLTests/ClientSNITests+XCTest.swift
  Tests/NIOSSLTests/ClientSNITests.swift
  Tests/NIOSSLTests/IdentityVerificationTest+XCTest.swift
  Tests/NIOSSLTests/IdentityVerificationTest.swift
  Tests/NIOSSLTests/NIOSSLALPNTest+XCTest.swift
  Tests/NIOSSLTests/NIOSSLALPNTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest+XCTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/NIOSSLTestHelpers.swift
  Tests/NIOSSLTests/SSLCertificateTest+XCTest.swift
  Tests/NIOSSLTests/SSLCertificateTest.swift
  Tests/NIOSSLTests/SSLPKCS12BundleTest+XCTest.swift
  Tests/NIOSSLTests/SSLPKCS12BundleTest.swift
  Tests/NIOSSLTests/SSLPrivateKeyTests+XCTest.swift
  Tests/NIOSSLTests/SSLPrivateKeyTests.swift
  Tests/NIOSSLTests/TLSConfigurationTest+XCTest.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
  Tests/NIOSSLTests/UnwrappingTests+XCTest.swift
  Tests/NIOSSLTests/UnwrappingTests.swift
Labels: needs-major-version-bump

#76 move uncleanShutdown error to NIOSSLError
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/SSLErrors.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/UnwrappingTests.swift
Labels: needs-major-version-bump

#79 Namespace header-only inline functions.
  Sources/CNIOBoringSSL/include/CNIOBoringSSL/ssl.h
  Sources/CNIOBoringSSL/include/boringssl_prefix_symbols.h
  Sources/CNIOBoringSSL/ssl/ssl_cert.cc
  scripts/vendor-boringssl.sh
Labels: patch-version-bump-only

#82 NIOSSLClientHandler: require serverHostname
  Sources/NIOSSL/NIOSSLClientHandler.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/UnwrappingTests.swift
Labels: needs-major-version-bump

#83 Record BoringSSL revision hash
  Package.swift
  Sources/CNIOBoringSSL/crypto/fipsmodule/vpaes-armv8.ios.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/vpaes-armv8.linux.aarch64.S
  Sources/CNIOBoringSSL/hash.txt
  scripts/vendor-boringssl.sh
Labels: patch-version-bump-only

#72 Enable TLS certificate validation on Apple platforms.
  Sources/NIOSSL/ByteBufferBIO.swift
  Sources/NIOSSL/NIOSSLClientHandler.swift
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/SSLConnection.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/SSLErrors.swift
  Sources/NIOSSL/SecurityFrameworkCertificateVerification.swift
  Tests/NIOSSLTests/NIOSSLTestHelpers.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: needs-major-version-bump

#84 flip role boolean
  Sources/NIOSSL/SecurityFrameworkCertificateVerification.swift
Labels: patch-version-bump-only

#32 Provide an http client example.
  .gitignore
  Package.swift
  Sources/NIOHTTP1Client/README.md
  Sources/NIOHTTP1Client/main.swift
Labels: needs-minor-version-bump

#85 Remove the static target from regular Package.swift.
  Package.swift
  docker/docker-compose.yaml
  scripts/vendor-boringssl.sh
Labels: patch-version-bump-only

#86 Clean up includes that were hidden by whitespace.
  Package.swift
  Sources/CNIOBoringSSL/crypto/fipsmodule/aes-armv4.ios.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/aes-armv4.linux.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/bsaes-armv7.ios.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/bsaes-armv7.linux.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha256-armv4.ios.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha256-armv4.linux.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha256-armv8.ios.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha256-armv8.linux.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha512-armv4.ios.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha512-armv4.linux.arm.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha512-armv8.ios.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha512-armv8.linux.aarch64.S
  scripts/vendor-boringssl.sh
Labels: patch-version-bump-only

#94 README: add links to API docs
  README.md
Labels: patch-version-bump-only

#95 API docs: repo switcher
  scripts/generate_docs.sh
Labels: patch-version-bump-only
