Repository apple/swift-nio-ssl, pull requests merged in 2020-10, with the labels that each got.

#246 Add `NIOSSLCertificate` debug description for useful debugging
  Sources/NIOSSL/SSLCertificate.swift
  Tests/NIOSSLTests/SSLCertificateTest+XCTest.swift
  Tests/NIOSSLTests/SSLCertificateTest.swift
Labels: 🔼 needs-minor-version-bump

#247 Add NIOSSLCertificate serial number var, and add to description
  Sources/NIOSSL/SSLCertificate.swift
  Tests/NIOSSLTests/SSLCertificateTest.swift
Labels: 🔼 needs-minor-version-bump

#250 Fix threading violation in KeyLogCallbackManager
  Sources/NIOSSL/SSLCallbacks.swift
  Tests/NIOSSLTests/TLSConfigurationTest+XCTest.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: patch-version-bump-only

#252 Add watchOS deployment to PodSpec build script
  scripts/build_podspec.sh
Labels: needs-no-version-bump
