Repository apple/swift-nio-ssl, pull requests merged in 2021-05, with the labels that each got.

#291 use 5.4 release instead of nightly
  docker/docker-compose.2004.54.yaml
Labels: needs-no-version-bump

#292 add Swift 5.5 job
  docker/docker-compose.2004.55.yaml
Labels: needs-no-version-bump

#280 Implement bestEffort functions for hashable and equatable.
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/TLSConfigurationTest+XCTest.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: 🔼 needs-minor-version-bump

#294 Explicit `time_t` import
  Sources/NIOSSL/SSLCertificate.swift
Labels: patch-version-bump-only

#298 Clean up new hashable implementation.
  Package.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/TLSConfigurationTest+XCTest.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: patch-version-bump-only

#295 docs: warn about NIOSSLContext being expensive to create
  Sources/NIOSSL/SSLContext.swift
Labels: needs-no-version-bump

#299 Rationalise TLSConfiguration construction.
  IntegrationTests/tests_02_allocation_counters/test_01_resources/test_many_writes.swift
  IntegrationTests/tests_02_allocation_counters/test_01_resources/test_simple_handshake.swift
  README.md
  Sources/NIOSSL/SSLPKCS12Bundle.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Sources/NIOSSL/UniversalBootstrapSupport.swift
  Sources/NIOSSLHTTP1Client/main.swift
  Sources/NIOSSLPerformanceTester/BenchManyWrites.swift
  Sources/NIOSSLPerformanceTester/BenchRepeatedHandshakes.swift
  Sources/NIOTLSServer/main.swift
  Tests/NIOSSLTests/ClientSNITests.swift
  Tests/NIOSSLTests/NIOSSLALPNTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/SSLPrivateKeyTests.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
  Tests/NIOSSLTests/UnwrappingTests.swift
Labels: 🔼 needs-minor-version-bump
