Repository apple/swift-nio-ssl, pull requests merged in 2021-09, with the labels that each got.

#313 Fix doc generation and jazzy version (#1950)
  docker/Dockerfile
  scripts/generate_docs.sh
Labels: needs-no-version-bump

#312 Support building in the Swift toolchain
  Package.swift
Labels: patch-version-bump-only

#307 issue-231: Adding CA Names to the TLS handshake.
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/NIOSSLTestHelpers.swift
  Tests/NIOSSLTests/TLSConfigurationTest+XCTest.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: 🔼 needs-minor-version-bump

#318 issue-317: Fix for nightly build.
  Tests/NIOSSLTests/ClientSNITests.swift
Labels: patch-version-bump-only

#319 Clean up imports and dependencies
  IntegrationTests/tests_02_allocation_counters/test_01_resources/run-nio-ssl-alloc-counter-tests.sh
  IntegrationTests/tests_02_allocation_counters/test_01_resources/shared.swift
  IntegrationTests/tests_02_allocation_counters/test_01_resources/test_many_writes.swift
  IntegrationTests/tests_02_allocation_counters/test_01_resources/test_simple_handshake.swift
  Package.swift
  Sources/NIOSSL/ByteBufferBIO.swift
  Sources/NIOSSL/IdentityVerification.swift
  Sources/NIOSSL/LinuxCABundle.swift
  Sources/NIOSSL/NIOSSLClientHandler.swift
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/NIOSSLServerHandler.swift
  Sources/NIOSSL/PosixPort.swift
  Sources/NIOSSL/SSLCallbacks.swift
  Sources/NIOSSL/SSLCertificate.swift
  Sources/NIOSSL/SSLConnection.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/SSLPKCS12Bundle.swift
  Sources/NIOSSL/SecurityFrameworkCertificateVerification.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Sources/NIOSSL/UniversalBootstrapSupport.swift
  Sources/NIOSSLHTTP1Client/main.swift
  Sources/NIOSSLPerformanceTester/BenchManyWrites.swift
  Sources/NIOSSLPerformanceTester/BenchRepeatedHandshakes.swift
  Sources/NIOSSLPerformanceTester/main.swift
  Sources/NIOSSLPerformanceTester/shared.swift
  Sources/NIOTLSServer/main.swift
  Tests/NIOSSLTests/ByteBufferBIOTest.swift
  Tests/NIOSSLTests/CertificateVerificationTests.swift
  Tests/NIOSSLTests/ClientSNITests.swift
  Tests/NIOSSLTests/IdentityVerificationTest.swift
  Tests/NIOSSLTests/NIOSSLALPNTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/SSLCertificateTest.swift
  Tests/NIOSSLTests/SSLPKCS12BundleTest.swift
  Tests/NIOSSLTests/SSLPrivateKeyTests.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
  Tests/NIOSSLTests/UnwrappingTests.swift
  scripts/soundness.sh
Labels: patch-version-bump-only

#321 Remove the implementationOnly dance
  Sources/NIOSSL/ByteBufferBIO.swift
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/SSLCallbacks.swift
  Sources/NIOSSL/SSLCertificate.swift
  Sources/NIOSSL/SSLConnection.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/SSLErrors.swift
  Sources/NIOSSL/SSLInit.swift
  Sources/NIOSSL/SSLPKCS12Bundle.swift
  Sources/NIOSSL/SSLPrivateKey.swift
  Sources/NIOSSL/SSLPublicKey.swift
  Sources/NIOSSL/SecurityFrameworkCertificateVerification.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/ByteBufferBIOTest.swift
  Tests/NIOSSLTests/NIOSSLALPNTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/NIOSSLTestHelpers.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: patch-version-bump-only

#320 Fixup CA name tests on Darwin
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: patch-version-bump-only

#322 Add callback-based custom private keys.
  Sources/NIOSSL/CustomPrivateKey.swift
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/SSLCallbacks.swift
  Sources/NIOSSL/SSLConnection.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/SSLErrors.swift
  Sources/NIOSSL/SSLPrivateKey.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/LinuxMain.swift
  Tests/NIOSSLTests/CustomPrivateKeyTests+XCTest.swift
  Tests/NIOSSLTests/CustomPrivateKeyTests.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/NIOSSLTestHelpers.swift
Labels: 🔼 needs-minor-version-bump

#323 Tolerate zeroReturnError in closed/unwrapped
  Sources/NIOSSL/NIOSSLHandler.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest+XCTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
Labels: patch-version-bump-only

#324 Migrate to Swift 5.5 release in CI
  docker/docker-compose.2004.55.yaml
Labels: needs-no-version-bump
