Repository apple/swift-nio-ssl, pull requests merged in 2021-03, with the labels that each got.

#278 Add SECURITY.md
  SECURITY.md
Labels: needs-no-version-bump

#279 Update boringssl to 04b3213d43492b6c9e0434d8e2a4530a9938f958
  Package.swift
  Sources/CNIOBoringSSL/crypto/cpu-arm-linux.c
  Sources/CNIOBoringSSL/crypto/cpu-arm.c
  Sources/CNIOBoringSSL/crypto/err/err_data.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/cipher/cipher.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/dh/dh.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/ec/ec.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/ec/ec_key.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/ec/internal.h
  Sources/CNIOBoringSSL/crypto/fipsmodule/ecdsa/ecdsa.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/ecdsa/internal.h
  Sources/CNIOBoringSSL/crypto/fipsmodule/rand/rand.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/self_check/self_check.c
  Sources/CNIOBoringSSL/crypto/pkcs8/pkcs8_x509.c
  Sources/CNIOBoringSSL/crypto/rand_extra/rand_extra.c
  Sources/CNIOBoringSSL/crypto/x509/internal.h
  Sources/CNIOBoringSSL/crypto/x509/x509_cmp.c
  Sources/CNIOBoringSSL/crypto/x509/x509_r2x.c
  Sources/CNIOBoringSSL/crypto/x509/x509_set.c
  Sources/CNIOBoringSSL/crypto/x509/x509_vfy.c
  Sources/CNIOBoringSSL/crypto/x509/x_attrib.c
  Sources/CNIOBoringSSL/crypto/x509/x_crl.c
  Sources/CNIOBoringSSL/crypto/x509/x_val.c
  Sources/CNIOBoringSSL/crypto/x509/x_x509.c
  Sources/CNIOBoringSSL/crypto/x509v3/v3_purp.c
  Sources/CNIOBoringSSL/hash.txt
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_base.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_boringssl_prefix_symbols.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_boringssl_prefix_symbols_asm.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_cipher.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_cpu.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_dh.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_ec.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_ecdsa.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_pkcs7.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_pkcs8.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_rand.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_ssl.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_x509.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_x509v3.h
  Sources/CNIOBoringSSL/include/boringssl_prefix_symbols_nasm.inc
  Sources/CNIOBoringSSL/ssl/ssl_lib.cc
  Sources/CNIOBoringSSL/ssl/t1_lib.cc
  scripts/vendor-boringssl.sh
Labels: patch-version-bump-only

#281 Call SecTrustEvaluateAsync from correct queue.
  Sources/NIOSSL/SecurityFrameworkCertificateVerification.swift
Labels: patch-version-bump-only

#282 Provide notValidBefore and notValidAfter.
  Sources/NIOSSL/SSLCertificate.swift
  Tests/NIOSSLTests/SSLCertificateTest+XCTest.swift
  Tests/NIOSSLTests/SSLCertificateTest.swift
Labels: 🔼 needs-minor-version-bump

#283 Add a correct docker-compose file for nightly
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump

#284 Add support for additional TLS trust roots
  Sources/NIOSSL/SSLConnection.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/SecurityFrameworkCertificateVerification.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/NIOSSLTestHelpers.swift
  Tests/NIOSSLTests/TLSConfigurationTest+XCTest.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: 🔼 needs-minor-version-bump
