Repository apple/swift-nio-ssl, pull requests merged in 2022-08, with the labels that each got.

#389 Make `NIOSSLCertificate._subjectAlternativeNames()` return type non-optional
  Sources/NIOSSL/IdentityVerification.swift
  Sources/NIOSSL/SSLCertificate.swift
  Sources/NIOSSL/SubjectAlternativeName.swift
  Tests/NIOSSLTests/SSLCertificateTest.swift
Labels: 🔼 needs-minor-version-bump

#391 Adopt `Sendable` in `SSLError.swift`
  Package.swift
  Sources/NIOSSL/SSLErrors.swift
Labels: 🔼 needs-minor-version-bump

#394 Update expired certs for CA name test.
  Tests/NIOSSLTests/NIOSSLTestHelpers.swift
Labels: needs-no-version-bump

#392 Adopt `Sendable` incrementally
  Package.swift
  Sources/NIOSSL/CustomPrivateKey.swift
  Sources/NIOSSL/NIOSSLClientHandler.swift
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/NIOSSLServerHandler.swift
  Sources/NIOSSL/ObjectIdentifier.swift
  Sources/NIOSSL/SSLCallbacks.swift
  Sources/NIOSSL/SSLCertificate.swift
  Sources/NIOSSL/SSLCertificateExtensions.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/SSLPKCS12Bundle.swift
  Sources/NIOSSL/SSLPrivateKey.swift
  Sources/NIOSSL/SSLPublicKey.swift
  Sources/NIOSSL/SubjectAlternativeName.swift
  Sources/NIOSSL/SwiftCrypto/NIOSSLSecureBytes.swift
  Sources/NIOSSL/TLSConfiguration.swift
Labels: 🔼 needs-minor-version-bump

#393 Store internal error file and line number information in error wrappers
  Sources/NIOSSL/SSLErrors.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
Labels: patch-version-bump-only

#395 Adopt `Sendable` incrementally
  Sources/NIOSSL/SSLCallbacks.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Sources/NIOSSL/UniversalBootstrapSupport.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
  Tests/NIOSSLTests/UnsafeTransfer.swift
Labels: 🔼 needs-minor-version-bump

#396 Validate missing imports in CI
  docker/docker-compose.2004.main.yaml
  docker/docker-compose.yaml
Labels: needs-no-version-bump

#397 Adopt `Sendable` for `TLSConfiguration`
  Sources/NIOSSL/TLSConfiguration.swift
Labels: 🔼 needs-minor-version-bump
