Repository apple/swift-nio-ssl, pull requests merged in 2022-09, with the labels that each got.

#398 Remove giant write test
  Sources/NIOSSL/NIOSSLClientHandler.swift
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/NIOSSLServerHandler.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest+XCTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/TLS13RecordObserver.swift
Labels: needs-no-version-bump

#400 Replace Lock with NIOLock
  Package.swift
  Package@swift-5.4.swift
  Package@swift-5.5.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
Labels: patch-version-bump-only

#401 Raise minimum supported Swift version from 5.4 to 5.5
  Package@swift-5.5.swift
  README.md
  Sources/NIOSSL/Docs.docc/index.md
  Tests/LinuxMain.swift
  docker/Dockerfile
  docker/docker-compose.1804.54.yaml
  docker/docker-compose.2004.57.yaml
  docker/docker-compose.2204.57.yaml
  scripts/generate_linux_tests.rb
Labels: 🔼 needs-minor-version-bump
