Repository apple/swift-nio-ssl, pull requests merged in 2022-01, with the labels that each got.

#336 Update BoringSSL to 295b31324f8c557dcd3c1c831857e33a7f23bc52
  Package.swift
  Sources/CNIOBoringSSL/crypto/bio/file.c
  Sources/CNIOBoringSSL/crypto/cpu_aarch64_apple.c
  Sources/CNIOBoringSSL/crypto/cpu_aarch64_fuchsia.c
  Sources/CNIOBoringSSL/crypto/cpu_aarch64_linux.c
  Sources/CNIOBoringSSL/crypto/cpu_aarch64_win.c
  Sources/CNIOBoringSSL/crypto/cpu_arm.c
  Sources/CNIOBoringSSL/crypto/cpu_arm_linux.c
  Sources/CNIOBoringSSL/crypto/cpu_arm_linux.h
  Sources/CNIOBoringSSL/crypto/cpu_intel.c
  Sources/CNIOBoringSSL/crypto/cpu_ppc64le.c
  Sources/CNIOBoringSSL/crypto/crypto.c
  Sources/CNIOBoringSSL/crypto/evp/print.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha256-armv8.ios.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha256-armv8.linux.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha512-armv8.ios.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/sha512-armv8.linux.aarch64.S
  Sources/CNIOBoringSSL/crypto/x509/t_crl.c
  Sources/CNIOBoringSSL/crypto/x509/t_req.c
  Sources/CNIOBoringSSL/crypto/x509/t_x509.c
  Sources/CNIOBoringSSL/crypto/x509/x509_set.c
  Sources/CNIOBoringSSL/crypto/x509/x509cset.c
  Sources/CNIOBoringSSL/crypto/x509/x509rset.c
  Sources/CNIOBoringSSL/crypto/x509/x_crl.c
  Sources/CNIOBoringSSL/crypto/x509/x_req.c
  Sources/CNIOBoringSSL/crypto/x509v3/v3_alt.c
  Sources/CNIOBoringSSL/crypto/x509v3/v3_ncons.c
  Sources/CNIOBoringSSL/crypto/x509v3/v3_utl.c
  Sources/CNIOBoringSSL/hash.txt
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_arm_arch.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_bio.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_boringssl_prefix_symbols.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_boringssl_prefix_symbols_asm.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_cpu.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_x509v3.h
  Sources/CNIOBoringSSL/include/boringssl_prefix_symbols_nasm.inc
  Sources/CNIOBoringSSL/ssl/ssl_privkey.cc
Labels: patch-version-bump-only

#339 Add 5.6 nightly CI.
  docker/docker-compose.2004.56.yaml
Labels: needs-no-version-bump

#338 Enhancement to address issue-337 to query the final `TLSVersion`
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/SSLConnection.swift
  Tests/NIOSSLTests/TLSConfigurationTest+XCTest.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: 🔼 needs-minor-version-bump

#341 Add `Hashable` conformance to `NIOSSLPKCS12Bundle`
  Sources/NIOSSL/SSLPKCS12Bundle.swift
  Tests/NIOSSLTests/SSLPKCS12BundleTest+XCTest.swift
  Tests/NIOSSLTests/SSLPKCS12BundleTest.swift
Labels: 🔼 needs-minor-version-bump
