Repository apple/swift-nio-ssl, pull requests merged in 2022-04, with the labels that each got.

#353 Drop support for Swift 5.2 and 5.3
  Package.swift
  README.md
  docker/Dockerfile
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1804.54.yaml
  docker/docker-compose.2004.54.yaml
  scripts/build_podspec.sh
  scripts/check_no_api_breakages.sh
Labels: 🔼 needs-minor-version-bump

#352 Add `NIOSSLObjectIdentifier` (OID) type
  Sources/NIOSSL/ObjectIdentifier.swift
  Sources/NIOSSL/String+unsafeUninitializedCapacity.swift
  Tests/NIOSSLTests/ObjectIdentifier.swift
Labels: 🔼 needs-minor-version-bump

#355 Fix warnings, that appeared after requiring Swift 5.4
  Package.swift
Labels: needs-no-version-bump

#356 Update BoringSSL to f299342e38fd34b589604ef5b730623da13ee235
  Package.swift
  Sources/CNIOBoringSSL/crypto/asn1/tasn_dec.c
  Sources/CNIOBoringSSL/crypto/bio/printf.c
  Sources/CNIOBoringSSL/crypto/bytestring/ber.c
  Sources/CNIOBoringSSL/crypto/bytestring/cbs.c
  Sources/CNIOBoringSSL/crypto/curve25519/curve25519.c
  Sources/CNIOBoringSSL/crypto/err/err_data.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/ec/ec.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/ec/p256-nistz-table.h
  Sources/CNIOBoringSSL/crypto/fipsmodule/ec/p256-nistz.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/ec/p256-nistz.h
  Sources/CNIOBoringSSL/crypto/fipsmodule/ec/p256.c
  Sources/CNIOBoringSSL/crypto/fipsmodule/p256-armv8-asm.ios.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/p256-armv8-asm.linux.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/p256_beeu-armv8-asm.ios.aarch64.S
  Sources/CNIOBoringSSL/crypto/fipsmodule/p256_beeu-armv8-asm.linux.aarch64.S
  Sources/CNIOBoringSSL/crypto/hrss/hrss.c
  Sources/CNIOBoringSSL/crypto/internal.h
  Sources/CNIOBoringSSL/crypto/mem.c
  Sources/CNIOBoringSSL/crypto/pkcs8/pkcs8_x509.c
  Sources/CNIOBoringSSL/crypto/poly1305/poly1305.c
  Sources/CNIOBoringSSL/crypto/x509/internal.h
  Sources/CNIOBoringSSL/crypto/x509/t_x509.c
  Sources/CNIOBoringSSL/crypto/x509/x509_cmp.c
  Sources/CNIOBoringSSL/crypto/x509/x509_trs.c
  Sources/CNIOBoringSSL/crypto/x509/x509_vfy.c
  Sources/CNIOBoringSSL/crypto/x509/x_crl.c
  Sources/CNIOBoringSSL/crypto/x509v3/v3_purp.c
  Sources/CNIOBoringSSL/hash.txt
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_boringssl_prefix_symbols.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_boringssl_prefix_symbols_asm.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_bytestring.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_pkcs8.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_span.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_stack.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_type_check.h
  Sources/CNIOBoringSSL/include/CNIOBoringSSL_x509.h
  Sources/CNIOBoringSSL/include/boringssl_prefix_symbols_nasm.inc
  Sources/CNIOBoringSSL/ssl/handshake_server.cc
  Sources/CNIOBoringSSL/ssl/internal.h
  Sources/CNIOBoringSSL/ssl/ssl_cipher.cc
  Sources/CNIOBoringSSL/ssl/ssl_key_share.cc
  Sources/CNIOBoringSSL/third_party/fiat/curve25519_32.h
  Sources/CNIOBoringSSL/third_party/fiat/curve25519_64.h
  Sources/CNIOBoringSSL/third_party/fiat/p256_32.h
  Sources/CNIOBoringSSL/third_party/fiat/p256_64.h
  scripts/vendor-boringssl.sh
Labels: patch-version-bump-only

#357 Remove non-generic generic.
  Sources/NIOSSL/SSLContext.swift
Labels: patch-version-bump-only

#358 Add support for owned references to `NIOSSLObjectIdentifier`
  Sources/NIOSSL/ObjectIdentifier.swift
  Tests/LinuxMain.swift
  Tests/NIOSSLTests/ObjectIdentifierTests+XCTest.swift
  Tests/NIOSSLTests/ObjectIdentifierTests.swift
Labels: patch-version-bump-only
