Repository apple/swift-nio-ssl, pull requests merged in 2022-07, with the labels that each got.

#379 Unbuffer reads after handshake
  Sources/NIOSSL/NIOSSLHandler.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest+XCTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
Labels: patch-version-bump-only

#383 Update the expired leaf certificate
  Tests/NIOSSLTests/SecurityFrameworkVerificationTests.swift
Labels: needs-no-version-bump

#384 Tolerate massive writes
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/SSLConnection.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest+XCTest.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
Labels: patch-version-bump-only

#386 Add sendCANameList to best effort functions.
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: patch-version-bump-only

#385 Clean up write logic
  Sources/NIOSSL/NIOSSLHandler.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
  Tests/NIOSSLTests/NIOSSLTestHelpers.swift
Labels: patch-version-bump-only

#369 Add TLS-PSK Support
  Sources/NIOSSL/SSLCallbacks.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/SwiftCrypto/NIOSSLSecureBytes.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/NIOSSLSecureBytesTests.swift
  Tests/NIOSSLTests/TLSConfigurationTest+XCTest.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: 🔼 needs-minor-version-bump

#387 Invoke `additionalPeerCertificateVerificationCallback` with peer certificate
  Sources/NIOSSL/NIOSSLClientHandler.swift
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/NIOSSLServerHandler.swift
  Sources/NIOSSL/SSLCallbacks.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/UniversalBootstrapSupport.swift
  Tests/NIOSSLTests/NIOSSLIntegrationTest.swift
Labels: needs-no-version-bump
