Repository apple/swift-nio-ssl, pull requests merged in 2024-09, with the labels that each got.

#479 Add release.yml
  .github/release.yml
Labels: semver/none

#480 Exclude privacy manifest when it isn't a resource
  Package.swift
Labels: semver/patch

#456 Implement SSL_CTX_set_cert_cb
  README.md
  Sources/NIOSSL/Docs.docc/index.md
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/SSLCallbacks.swift
  Sources/NIOSSL/SSLConnection.swift
  Sources/NIOSSL/SSLContext.swift
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/SSLContextTests.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
  scripts/soundness.sh
Labels: semver/minor
