Repository apple/swift-nio-ssl, pull requests merged in 2025-04, with the labels that each got.

#517 Enable macOS CI on pull requests
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#520 Update test certs
  Tests/NIOSSLTests/SecurityFrameworkVerificationTests.swift
Labels: 🔨 semver/patch

#519 Switch integration tests to newer Swift test matrix
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#526 Clarify that we don't hop ELs in our callbacks
  Sources/NIOSSL/CustomPrivateKey.swift
  Sources/NIOSSL/SSLCallbacks.swift
Labels: 🔨 semver/patch

#525 Cleanup missing internal Sendable annotation and missing preconcurrency import
  Sources/NIOSSL/SecurityFrameworkCertificateVerification.swift
  Sources/NIOSSL/SubjectAlternativeName.swift
Labels: 🔨 semver/patch

#523 Clean up sendability of statics
  Sources/NIOSSL/ByteBufferBIO.swift
  Sources/NIOSSL/CustomPrivateKey.swift
  Sources/NIOSSL/PosixPort.swift
  Sources/NIOSSL/SSLContext.swift
Labels: 🔨 semver/patch

#524 Clean up Sendability errors in pipelines and promises
  Benchmarks/Thresholds/5.10/NIOSSHBenchmarks.SimpleHandshake.p90.json
  Benchmarks/Thresholds/5.9/NIOSSHBenchmarks.SimpleHandshake.p90.json
  Benchmarks/Thresholds/6.0/NIOSSHBenchmarks.SimpleHandshake.p90.json
  Benchmarks/Thresholds/nightly-main/NIOSSHBenchmarks.SimpleHandshake.p90.json
  Benchmarks/Thresholds/nightly-next/NIOSSHBenchmarks.SimpleHandshake.p90.json
  Sources/NIOSSL/NIOSSLHandler.swift
Labels: 🔨 semver/patch

#527 Fix sendability issues in Universal Bootstrap
  Sources/NIOSSL/UniversalBootstrapSupport.swift
Labels: 🔨 semver/patch

#522 Remove some redundant suppressed conformances
  Sources/NIOSSL/NIOSSLClientHandler.swift
  Sources/NIOSSL/NIOSSLServerHandler.swift
Labels: 🔨 semver/patch

#528 Clean up Sendability issues in examples & performance tester
  Sources/NIOSSLHTTP1Client/main.swift
  Sources/NIOSSLPerformanceTester/BenchManyWrites.swift
  Sources/NIOSSLPerformanceTester/BenchRepeatedHandshakes.swift
  Sources/NIOSSLPerformanceTester/main.swift
  Sources/NIOTLSServer/main.swift
Labels: semver/none

#531 Enable Swift 6.1 jobs in CI
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#532 Add DocC extension page to provide curation for TLSConfiguration
  Sources/NIOSSL/Docs.docc/TLSConfiguration.md
Labels: semver/none

#534 Fix typo in NIOSSLServerHandler documentation.
  Sources/NIOSSL/NIOSSLServerHandler.swift
Labels: semver/none

#533 Add subjectName, issuerName, and access to the peerCert
  Sources/NIOSSL/NIOSSLHandler.swift
  Sources/NIOSSL/SSLCertificateName.swift
  Tests/NIOSSLTests/SSLCertificateTest.swift
Labels: 🆕 semver/minor

#535 Add explicit API support for X25519_MLKEM768 hybrid KEM
  Sources/NIOSSL/Docs.docc/index.md
  Sources/NIOSSL/Docs.docc/quantum-secure-tls.md
  Sources/NIOSSL/TLSConfiguration.swift
  Tests/NIOSSLTests/TLSConfigurationTest.swift
Labels: 🆕 semver/minor
